apiVersion: v1
kind: ConfigMap
metadata:
  name: gnmic-config
data:
  config.yaml: |

    username: admin
    password: admin
    insecure: true
    encoding: json_ietf
    log: true

    targets:
      172.18.100.2:57400:
        username: admin
        password: admin
      172.18.100.3:57400:
        username: admin
        password: admin
      172.18.100.4:57400:
        username: admin
        password: admin
      172.18.100.5:57400:
        username: admin
        password: admin

    subscriptions:
      sros_port_stats_eth3:
        paths:
          - /state/port[port-id=1/1/c3/1]/statistics
        mode: stream
        stream-mode: sample
        sample-interval: 5s

      sros_port_stats_eth5:
        paths:
          - /state/port[port-id=1/1/c5/1]/statistics
        mode: stream
        stream-mode: sample
        sample-interval: 5s

      sros_last-reported-delay:
        paths:
          - /state/test-oam/link-measurement/router[router-instance=Base]/interface/last-reported-delay
        mode: stream
        stream-mode: sample
        sample-interval: 5s

    outputs:
      prom:
        type: prometheus
        path: /metrics
        metric-prefix: gnmic
        append-subscription-name: true
        export-timestamps: true
        debug: false
        event-processors:
          - trim-prefixes
          - up-down-map

    processors:
      trim-prefixes:
        event-strings:
          value-names:
            - ".*"
          transforms:
            - path-base:
                apply-on: "name"
      up-down-map:
        event-strings:
          value-names:
            - oper-state
          transforms:
            - replace:
                apply-on: "value"
                old: "up"
                new: "1"
            - replace:
                apply-on: "value"
                old: "down"
                new: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: gnmic-login
type: Opaque
stringData:
  GNMIC_PASSWORD: admin
  GNMIC_USERNAME: admin
---
apiVersion: v1
kind: Service
metadata:
  name: gnmic-svc
  labels:
    app: gnmic
spec:
  type: NodePort  
  ports:
  - name: http
    port: 9804
    protocol: TCP
    targetPort: 9804
    nodePort: 30100  
  selector:
    app: gnmic
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gnmic-ss
  labels:
    app: gnmic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnmic
  serviceName: gnmic-svc
  template:
    metadata:
      labels:
        app: gnmic
    spec:
      containers:
        - args:
            - subscribe
            - --config
            - /app/config.yaml
          image: ghcr.io/karimra/gnmic
          imagePullPolicy: Never
          name: gnmic
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - containerPort: 9804
              name: prom-output
              protocol: TCP
            - containerPort: 7890
              name: gnmic-api
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 50m
              memory: 200Mi
          envFrom:
            - secretRef:
                name: gnmic-login
          env:
            - name: GNMIC_API
              value: :7890
            - name: PROM_OUTPUT
              value: :9804
          volumeMounts:
            - mountPath: /app/config.yaml
              name: config
              subPath: config.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: gnmic-config
          name: config
